spring.liquibase.enabled=false

# banking
app.datasource.banking.jdbc-url=${BANKING_DB_URL}
app.datasource.banking.username=${BANKING_DB_USERNAME}
app.datasource.banking.password=${BANKING_DB_PASSWORD}
app.datasource.banking.driver-class-name=org.postgresql.Driver

app.jpa.banking.hibernate.hbm2ddl.auto=none
app.jpa.banking.hibernate.show_sql=true
app.jpa.banking.hibernate.format_sql=true
app.jpa.banking.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#app.datasource.messenger.jdbc-url=${MESSENGER_DB_URL}
#app.datasource.messenger.username=${MESSENGER_DB_USERNAME}
#app.datasource.messenger.password=${MESSENGER_DB_PASSWORD}
#app.datasource.messenger.driver-class-name=org.postgresql.Driver

#app.datasource.social.jdbc-url=${SOCIAL_DB_URL}
#app.datasource.social.username=${SOCIAL_DB_USERNAME}
#app.datasource.social.password=${SOCIAL_DB_PASSWORD}
#app.datasource.social.driver-class-name=org.postgresql.Driver