<?xml version="1.0" encoding="UTF-8" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.phyllosedis</groupId>
        <artifactId>platform</artifactId>
        <version>0.0.2-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>app</artifactId>

    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.phyllosedis</groupId>
            <artifactId>banking-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.phyllosedis</groupId>
            <artifactId>messenger-api</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.phyllosedis</groupId>
            <artifactId>social-api</artifactId>
        </dependency>

        <dependency>
            <groupId>ru.phyllosedis</groupId>
            <artifactId>messenger-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.phyllosedis</groupId>
            <artifactId>banking-impl</artifactId>
        </dependency>
        <dependency>
            <groupId>ru.phyllosedis</groupId>
            <artifactId>social-impl</artifactId>
        </dependency>

        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>